---
title: "Getting and Cleaning Data Course Project"
author: "James Marino"
date: "2024-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The output files were taken using data pulled from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip. This is data related to an experiment where volunteers performed various activities wearing a smartphone strapped to their waist (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING). Measurements were then captured during these activities

The measurements in the initial dataset were split into test and training data. The x_train/x_test files contain all of the measurements done per subject per activity. They do not have an ID column, but can be joined with the y_train/y_test files via row number. The y_train/y_test files then contain the activity performed for each observation. These can be linked with the activity_labels file which contains each activity and its corresponding ID column. 

I also used the features.txt file to rename the columns loaded from the x_train/x_test files. At the end, I selected only the Activity column with the activity descriptions and the columns representing variables related to standard deviation and mean. These columns are below: 

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

(each variable above with 'XYZ' at the end has three separate columns in the dataset corresponding to each axial dimension represented by those letters)

I then wrote this dataset into a csv called test_and_training_data. 

After that, I created a new dataframe that groups each variable by the mean per activity. I then wrote this to another csv called means_by_activity.csv